const category = require("../../middlewares/client/category.middleware");
const cart = require("../../middlewares/client/cart.middleware");
const auth = require("../../middlewares/client/auth.middleware");
const setting = require("../../middlewares/client/setting.middleware");
const homeRoute = require("./home.route");
const productRoute = require("./product.route");
const searchRoute = require("./search.route");
const cartRoute = require("./cart.route");
const checkoutRoute = require("./checkout.route");
const loginRoute = require("./auth.route");
const chatRoute = require("./chat.route");
const authMiddleware = require("../../middlewares/client/user.middleware");
module.exports = (app) => {
  app.use(category.category);
  app.use(cart.cartId);
  app.use(auth.infoUser);
  app.use(setting.settingGeneral);
  app.use("/", homeRoute);
  app.use("/products", productRoute);
  app.use("/search", searchRoute);
  app.use("/cart", cartRoute);
  app.use("/checkout", checkoutRoute);
  app.use("/user", loginRoute);
  app.use("/chat", authMiddleware.requireAuth, chatRoute);
};
