const express = require("express");
const router = express.Router();
const roleController = require("../../controllers/admin/role.controller");
router.get("/", roleController.role);
router.get("/create", roleController.create);
router.post("/create", roleController.createRole);
router.get("/edit/:id", roleController.edit);
router.patch("/edit/:id", roleController.editRole);
router.delete("/delete/:id", roleController.deletedRole);
router.get("/permissions", roleController.permissions);
router.patch("/permissions", roleController.permissionsPatch);
module.exports = router;
